### ISSUE TITLE
Add form to simulate a new Finite Payment using Total

### ISSUE THREAD

**Issue by kieran-ohara** [kieran-ohara/mhawk#1]
# Story

```
As a user with an upcoming financial commitments 

I want to simulate a new commitment by submitting:
The total cost of the commitment
The starting month of the commitment
The ending month of the commitment

So that the total cost can be divided over the period of the commitment 
And I can see the effect this has on my Monthly Outgoings before committing to it.
```

# Tasks
- [x] Add Payment Plan mutations to local storage
- [x] Show the Payment Plan mutations in the Montly Outgoings view
- [x] Create the form
- [x] Add the new Payment Plan mutation on submit
- [x] Add a button in the Finite Payment page to summon the form
