### ISSUE TITLE
Allow user to create new Finite Payment using monthly amount

### ISSUE THREAD

**Issue by kieran-ohara** [kieran-ohara/mhawk#13]
# Story

```
As a user with an upcoming financial commitments 

I want to simulate a new commitment by submitting:
The monthly cost of the commitment
The starting month of the commitment
The ending month of the commitment

So that I can see the effect this has on my Monthly Outgoings before committing to it.
```

# Tasks
- [x] Create the form
- [x] Add the new Payment Plan mutation on submit
- [x] Add a button in the Finite Payment page to summon the form
