### ISSUE TITLE
Update database to support arbitrary tags

### ISSUE THREAD

**Issue by kieran-ohara** [kieran-ohara/mhawk#19]
# Tasks
- [x] Update Database to use tags
- [x] Update app to query database using "shared" tag instead of `is_shared`
- [x] Update app to show all tags in  sidebar
