### ISSUE TITLE
Allow user to tag and untag payment plans

### ISSUE THREAD

**Issue by kieran-ohara** [kieran-ohara/mhawk#26]
# Story

```
As a user
I want to tag my payment plans
So that I group them how in a way that makes sense to me
```

# Tasks
- [x] Create API for getting tags on a payment plan
- [x] Create API endpoint for adding tags to a payment plan
- [x] Create API endpoint for deleting tags to a payment plan
- [x] Create form showing checkboxes of tags for a payment plan;  boes are checked if the tag is applied to payment plan
- [ ] When the checkbox is checked/unchecked, add/remove tag from payment plan accordingly.
