### ISSUE TITLE
Protect data using AuthO/AuthZ from application instead of K8S Ingress

### ISSUE THREAD

**Issue by kieran-ohara** [kieran-ohara/mhawk#30]
# Story

```
As a user
I want my data to be protected by application login instead of Kubernetes Ingress
So that I don't have to fiddle with Kube config every time I want to edit my data.

As a user
I want to be able to login with Monzo
So that I don't have to setup up a new account with a new email and password

As a user
I want to be able to logout of my account
So that other users are not able to edit my data by using the computer after me

As an app admin
I want to be the only person that is able to log in to the app
So that I am the only person that is able to make changes to the data
```

# Tasks
- [x] Add capability for login with Monzo
- [x] Restrict to loggin in with me
- [x] Add capability for logout 
- [x] Protect access to app by enforcing login
- [x] Protect data by auth'ing API endpoints
- [x] Lift Ingress restrictions.
