### ISSUE TITLE
Add ability to search for payment plans

### ISSUE THREAD

**Issue by kieran-ohara** [kieran-ohara/mhawk#33]
# Story

```
As a user
I want payment plans suggested to me as I type their reference name
So that I don't have to remember exact reference names

As a user
I want to be able to jump to suggested payment plans
So that I can readily view/modify the plans that are suggested to me

As a user
I want to be able to search for payment plans
So that I don't have to scan large sets of rows to find what I need
```

# Tasks
- [ ] Index payment plans
- [ ] Create search endpoint
- [ ] Create search as you type box 
- [ ] On click of search result goto payment plan
