### ISSUE TITLE
Hide completed finite payments

### ISSUE THREAD

**Issue by kieran-ohara** [kieran-ohara/mhawk#36]
# Story

```
As a user
I want completed finite payments to be hidden
So that I can focus on what is important
```

# Tasks
- [ ] hide completed payments from finite payments view
- [ ] hide completed payments from tag view
- [ ] do payments need removing from complete view?

**Comment by kieran-ohara** [comment]
+1
